"use client";

import Link from "next/link";
import { ArrowUpRight, Check, CircleAlert, Database, Gavel, LockKeyhole, Scale } from "lucide-react";
import { getUpholdContractAddress, UPHOLD_NETWORK } from "@/lib/uphold/config";
import { useContractInfo } from "@/lib/uphold/hooks";
import { ExternalLinkLabel, PageHeader } from "./ui";

export function TransparencyContent() {
  const info = useContractInfo();
  return <>
    <PageHeader eyebrow="Transparency" title="The protocol is opinionated about what belongs on-chain." copy="Uphold separates evidence authentication, semantic judgment, lifecycle state, and value movement so no single uncertain component can punish a promisor." action={getUpholdContractAddress() ? <ExternalLinkLabel href={`${UPHOLD_NETWORK.explorerUrl}address/${getUpholdContractAddress()}`}>View contract <ArrowUpRight size={14} /></ExternalLinkLabel> : undefined} />
    <section className="transparency-hero"><div className="trust-diagram"><TrustNode icon={<Database />} label="Authenticated live snapshot" /><span className="diagram-arrow">→</span><TrustNode icon={<Scale />} label="Bounded semantic judgment" /><span className="diagram-arrow">→</span><TrustNode icon={<LockKeyhole />} label="Deterministic settlement" /></div><p>Validators never get to choose the beneficiary, calculate payment, or bypass a deadline.</p></section>
    <div className="transparency-grid">
      <section className="content-panel"><p className="eyebrow">Validator boundary</p><h2>What validators decide</h2><p>Given the original commitment, the immutable baseline snapshot, and a new authenticated live-source snapshot, validators classify only their semantic relationship:</p><div className="classification-list"><div><span className="classification classification-holds">HOLDS</span><p>The current source still substantially carries the commitment.</p></div><div><span className="classification classification-weakened">WEAKENED</span><p>The promise remains recognizable but is materially narrowed or reduced.</p></div><div><span className="classification classification-absent">ABSENT</span><p>The independently authenticated source no longer contains the committed promise.</p></div><div><span className="classification classification-indeterminate">INDETERMINATE</span><p>The authenticated snapshots are insufficient for the bounded judgment.</p></div></div></section>
      <section className="content-panel"><p className="eyebrow">Deterministic boundary</p><h2>What validators do not decide</h2><ul className="check-list"><li><Check size={15} /> Authorization or beneficiary identity</li><li><Check size={15} /> Source URL, status, byte limit, or hashing</li><li><Check size={15} /> Deadlines, contest windows, or expiry</li><li><Check size={15} /> Stake arithmetic, payment amount, or settlement</li><li><Check size={15} /> Whether a finalized transaction is application success</li></ul></section>
      <section className="content-panel"><p className="eyebrow">Evidence pipeline</p><h2>Authenticated before interpreted</h2><div className="pipeline-list"><PipelineStep number="01" title="Live baseline" copy="At creation, validators fetch the exact registered source URL and agree on status, full-response hash, byte length, timestamp, and bounded text." /><PipelineStep number="02" title="Immutable snapshot" copy="The agreed baseline is stored once; later checks create new write-once snapshots for the same source URL." /><PipelineStep number="03" title="Semantic question" copy="Validators compare stored baseline and current snapshots. The semantic step performs no additional live fetch." /><PipelineStep number="04" title="Audit entry" copy="Classification, digest, excerpt, and streak effect are recorded without making explanation prose authoritative." /></div></section>
      <section className="content-panel"><p className="eyebrow">Safety rails</p><h2>Fail closed, then let people contest.</h2><p>Source outages, access restrictions, validator disagreement, malformed responses, and model errors remain distinct failure domains. None become ABSENT and none increment the breach streak.</p><div className="rule-callout"><CircleAlert size={18} /><span>A breach claim requires two consecutive, distinct, qualified negative snapshots. One negative observation cannot move money.</span></div><div className="rule-callout"><Gavel size={18} /><span>The promisor can request one fresh authenticated capture of the locked source. Contest evidence remains pending semantic adjudication until consensus completes.</span></div></section>
    </div>
    <section id="deployment" className="deployment-panel"><div><p className="eyebrow">Current deployment</p><h2>{getUpholdContractAddress() ? "Contract configured" : "Not yet deployed"}</h2><p>{getUpholdContractAddress() ? getUpholdContractAddress() : "No contract address is configured and no chain writes are performed."}</p></div><div className="deployment-meta"><span>{UPHOLD_NETWORK.name}</span><strong>Chain {UPHOLD_NETWORK.chainId}</strong><code>{UPHOLD_NETWORK.rpcUrl}</code>{info.data && <span>Protocol {info.data.version}</span>}</div></section>
    <p className="transparency-foot">Read the source and audit history in the repository. <Link href="/app/explore">Explore the application <ArrowUpRight size={14} /></Link></p>
  </>;
}

function TrustNode({ icon, label }: { icon: React.ReactNode; label: string }) { return <div className="trust-node"><span>{icon}</span><strong>{label}</strong></div>; }
function PipelineStep({ number, title, copy }: { number: string; title: string; copy: string }) { return <div className="pipeline-step"><span>{number}</span><div><strong>{title}</strong><p>{copy}</p></div></div>; }
